version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
      -
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /www/web:/usr/share/nginx/html
    ports:
      - "80:80"
    links:
      - php:php

  postgresql:
    image: postgresql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /data/postgresql:/var/lib/postgresql
    environment:
      ROOT_PASSWORD: root

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
    command: redis-server --appendonly yes
